name: Release binaries for Windows

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Binstall
        uses: cargo-bins/cargo-binstall@main

      - name: install Tauri
        run: cargo binstall tauri-cli --no-confirm

      - name: npm install (desktop)
        working-directory: desktop
        run: npm install

      - name: npm install (librqbit/webui)
        working-directory: crates/librqbit/webui
        run: npm install

      - name: cargo tauri build
        working-directory: desktop
        run: cargo tauri build --ci

      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            target/release/bundle/msi/rqbit-desktop_*_x64_en-US.msi

      - name: Build release
        run: cargo build --profile release-github

      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            target/release-github/rqbit.exe
